// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOOzagNEbBSGxT100L06yjWYkT6Mn11i4',
    appId: '1:527867693838:web:8c1dcf4389d9497005e55f',
    messagingSenderId: '527867693838',
    projectId: 'lab3-6741e',
    authDomain: 'lab3-6741e.firebaseapp.com',
    storageBucket: 'lab3-6741e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9HJ7DB99Qs_WSt3HywAE-d77o4Es8tu0',
    appId: '1:527867693838:android:f8a23dd0bacdf29405e55f',
    messagingSenderId: '527867693838',
    projectId: 'lab3-6741e',
    storageBucket: 'lab3-6741e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQYtX_LTFVU6doiWu9mClHIxTA2wk3iHI',
    appId: '1:527867693838:ios:f0da6f0d64450af905e55f',
    messagingSenderId: '527867693838',
    projectId: 'lab3-6741e',
    storageBucket: 'lab3-6741e.firebasestorage.app',
    iosBundleId: 'com.example.lab3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQYtX_LTFVU6doiWu9mClHIxTA2wk3iHI',
    appId: '1:527867693838:ios:f0da6f0d64450af905e55f',
    messagingSenderId: '527867693838',
    projectId: 'lab3-6741e',
    storageBucket: 'lab3-6741e.firebasestorage.app',
    iosBundleId: 'com.example.lab3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOOzagNEbBSGxT100L06yjWYkT6Mn11i4',
    appId: '1:527867693838:web:96b030743204207d05e55f',
    messagingSenderId: '527867693838',
    projectId: 'lab3-6741e',
    authDomain: 'lab3-6741e.firebaseapp.com',
    storageBucket: 'lab3-6741e.firebasestorage.app',
  );
}
